services:
  api1:
    hostname: api1
    build:
      context: .
      target: dev
    command: npm run dev
    ports:
      - '8888'
    user: node
    volumes:
      - ./:/opt/node_app/app
      - notused:/opt/node_app/app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=8888
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DATABASE=${DATABASE}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
    depends_on:
      - db
    networks:
      - application_network
    deploy:
      resources:
        limits:
          cpus: '0.75'
          memory: '1GB'

  api2:
    hostname: api2
    build:
      context: .
      target: dev
    command: npm run dev
    ports:
      - '8888'
    user: node
    volumes:
      - ./:/opt/node_app/app
      - notused:/opt/node_app/app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=8888
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DATABASE=${DATABASE}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
    depends_on:
      - db
    networks:
      - application_network
    deploy:
      resources:
        limits:
          cpus: '0.75'
          memory: '1GB'

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - '8080:8080'
    networks:
      - application_network
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '1GB'

  db:
    image: 'postgres:16.1'
    restart: always
    user: postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DATABASE}
    networks:
      - application_network
    volumes:
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
      - db:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: '4GB'

  redis:
    image: redis:latest
    ports:
      - '6379:6379'
    networks:
      - application_network
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '1GB'

networks:
  application_network:
    driver: bridge

volumes:
  notused:
  db:
